#!/bin/sh

SELECTION=CLIPBOARD
STORAGE="$HOME/.cache/xclipring/$SELECTION"
cd -- "$STORAGE"
ENTRY=$(find -type f -printf '%T@ %f\0' |
               sort -zk 1nr |
               sed -z 's:^[^ ]* ::' |
               xargs -P 1 -n 1 -0 xclipring-simplify |
               rofi -p 'xclipring' -no-levenshtein-sort -dmenu -columns 2 |
               cut -d':' -f1)
[ -z "$ENTRY" ] && exit 1
xclip -i -selection clipboard "$STORAGE/$ENTRY"
